version: '3.8'

services:
  postgres:
    image: debezium/postgres:15
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=pgsync
      - POSTGRES_PASSWORD=PLEASE_CHANGE_ME
      - POSTGRES_DB=postgres
  redis:
    image: redis
    command: redis-server --requirepass PLEASE_CHANGE_ME
  opensearch:
    image: opensearchproject/opensearch:latest
    ports:
      - "9400:9200"
      - "9600:9600"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
  pgsync:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./runserver.sh
    sysctls:
      - net.ipv4.tcp_keepalive_time=200
      - net.ipv4.tcp_keepalive_intvl=200
      - net.ipv4.tcp_keepalive_probes=5
    labels:
      org.label-schema.name: "pgsync"
      org.label-schema.description: "Postgres to OpenSearch sync"
      com.label-schema.service-type: "daemon"
    depends_on:
      - postgres
      - redis
      - opensearch
    environment:
      - PG_USER=pgsync
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_PASSWORD=PLEASE_CHANGE_ME
      - LOG_LEVEL=INFO
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_SCHEME=http
      - ELASTICSEARCH_HOST=opensearch
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_AUTH=PLEASE_CHANGE_ME
      - ELASTICSEARCH=false
      - OPENSEARCH=true
