name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Log into GitHub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image to GitHub Container Registry
      id: build-push-image
      run: |
        docker build -f Dockerfile . -t ghcr.io/${{ github.repository }}:latest
        docker push ghcr.io/${{ github.repository }}:latest
        echo "::set-output name=image::ghcr.io/${{ github.repository }}:latest"
